# Artificial Neural Network

Importing the Libraries 

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Preprocessing

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding Categorical Data

Encoding the 'Gender' Column 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot encoding the 'Geography' Column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into training and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the input layer and first Hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

# Training the ANN

Compiling The ANN

In [ ]:
ann.compile(optimizer ='adam', loss ='binary_crossentropy', metrics=['accuracy'] )

Training ANN on training set

In [ ]:
ann.fit(X_train,y_train, batch_size= 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5861 - accuracy: 0.7375
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4794 - accuracy: 0.7993
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4498 - accuracy: 0.8079
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4318 - accuracy: 0.8146
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4123 - accuracy: 0.8207
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3934 - accuracy: 0.8328
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3810 - accuracy: 0.8421
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3724 - accuracy: 0.8464
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3665 - accuracy: 0.8470
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3619 - accura

# Making the predictions and Evaluating the predictions.

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


Therfore the probability that the customer leavs the bank is low.

Predicting the test Results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_pred),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1529   56]
 [ 210  205]]


0.867